config/routes.rb
Rails.application.routes.draw do


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :update] #:idを持たせないためresouce
    get "/customers/information/edit" => "customers#edit"
    get "/customers/confirm" => "customers#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :update, :destroy]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/confirm" => "orders#error"
    get "/orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  get '/genre/search' => 'searches#genre_search'

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "/orders/detail/:id" => "orders#detail"
    patch "/admin/order_details/:id" => "order_details#update" ,as: "order_details"
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image
  validates :name, presence:true

  validates :description, presence:true

  validates :price, presence:true, numericality: {only_integer: true, greater_than_or_equal_to: 1}

    # 商品画像のサイズ調整
  def get_item_image(width, height)
    unless item_image.attached?
      # 商品画像がない場合はimages/no-image.jpgを参照
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end


  def with_tax_price
    (price * 1.1).floor
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "登録しました。"
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "変更しました。"
    else
      render :edit
    end
  end

  def item_params
        params.require(:item).permit(:item_image, :name, :description, :genre_id, :price, :is_on_sale)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<div class="row justify-content-center">
<%= form_with model: [ :admin, item ], local: true do |f| %>
  <table class="table table-borderless">
    <tr>
      <td><%= f.label :商品画像 %></td>
      <td><%= f.file_field :item_image, accept: "image/*" %></td>
      <td></td>
    </tr>
    <tr>
      <td><%= f.label :商品名 %></td>
      <td><%= f.text_field :name, placeholder: "商品名", class: "form-control" %></td>
      <td></td>
    </tr>
    <tr>
      <td><%= f.label :商品説明 %></td>
      <td><%= f.text_area :description, placeholder: "ここに説明文を記述します", class: "form-control", rows: 5 %></td>
      <td></td>
    </tr>
    <tr>
      <td><%= f.label :ジャンル %></td>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--", class: "form-control" %></td>
      <td></td>
    </tr>
    <tr>
      <td><%= f.label :税抜価格 %></td>
      <td><%= f.text_field :price, placeholder: "1000", class: "form-control" %></td>
      <td>円</td>
    </tr>
    <tr>
      <td><%= f.label :販売ステータス %></td>
      <td>
        <%= f.radio_button :is_on_sale, true %>
        <%= f.label :is_on_sale, "販売中" %>
        <%= f.radio_button :is_on_sale, false %>
        <%= f.label :is_on_sale_false, "販売停止" %>
      </td>
    </tr>
  </table>
  <div class="actions text-center">
  <% if item.new_record? %>
    <%= f.submit '新規登録', class: "btn btn-dark px-4" %>
  <% else %>
  　<%= f.submit '変更を保存', class: "btn btn-dark px-4" %>
  <% end %>
  </div>
<% end %>
</div>

app/views/admin/items/edit.html.erb
<div class="container py-5">
  <div class="row mt-3 mb-3 offset-1 text-center">
    <h3 class="px-4 title-background">商品編集</h3>
  </div>
  <div class="row justify-content-center">
    <%= render 'layouts/error', obj: @item %>
  </div>
  <%= render 'form', item: @item %>
</div>

app/views/admin/items/index.html.erb
<div class="container py-5">
<h3>商品一覧</h3>
  <div class="row justify-content-end mb-3">
    <div class="col-2">
      <%= link_to '+', new_admin_item_path, class: "title-background btn rounded-circle border-right border-bottom shadow btn-dark" %>
    </div>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id), class: "text-reset" %></td>
        <td><%= item.price.to_s(:delimited) %></td>
        <td><%= item.genre.name %></td>
        <td>
          <% if item.is_on_sale %>
              <p class="text-success"><strong>販売中</strong></p>
            <% elsif %>
              <p class="text-muted"><strong>販売停止中</strong></p>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="row justify-content-center">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container py-5">
  <div class="row mt-3 mb-3 offset-1 text-center">
    <h3 class="px-4 title-background">商品新規登録</h3>
  </div>
  <div class="row justify-content-center">
    <%= render 'layouts/error', obj: @item %>
  </div>
  <%= render 'form', item: @item %>
</div>

app/views/admin/items/show.html.erb
<div class="container py-5">
  <h3>商品詳細</h3>
  <div class="row justify-content-center">
    <%= image_tag @item.get_item_image(300,250) %>
  <table class="table table-borderless text-center">
    <tr>
      <td>商品名</td>
      <td><%= @item.name %></td>
    <tr>
      <td>商品説明</td>
      <td><%= simple_format(@item.description) %></td>
    </tr>
    <tr>
      <td>ジャンル</td>
      <td><%= @item.genre.name %></td>
    </tr>
    <tr>
      <td>
        税込価格<br>
        (税抜価格)
      </td>
      <td>
        <%= number_to_currency(@item.with_tax_price, format: "%n") %>
        (<%= number_to_currency(@item.price, format: "%n") %>)円
      </td>
    </tr>
    <tr>
      <td>販売ステータス</td>
      <td>
        <%= @item.is_on_sale ? '販売中' : '販売停止中' %>
      </td>
    </tr>
  </table>
  </div>
  <div class="row justify-content-center">
    <%= link_to '編集する', edit_admin_item_path(@item), class: "btn btn-dark px-4" %>
  </div>
</div>