config/routes.rb
Rails.application.routes.draw do


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :update] #:idを持たせないためresouce
    get "/customers/information/edit" => "customers#edit"
    get "/customers/confirm" => "customers#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :update, :destroy]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/confirm" => "orders#error"
    get "/orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  get '/genre/search' => 'searches#genre_search'

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "/orders/detail/:id" => "orders#detail"
    patch "/admin/order_details/:id" => "order_details#update" ,as: "order_details"
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :customer_id, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders,     dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses,  dependent: :destroy

  validates :last_name,         presence: true, length: {maximum: 20}
  validates :last_name_kana,    presence: true, length: {maximum: 20}, format: { with: /\A[\p{katakana}\u{30fc}]+\z/ }
  validates :first_name,        presence: true, length: {maximum: 20}
  validates :first_name_kana,   presence: true, length: {maximum: 20}, format: { with: /\A[\p{katakana}\u{30fc}]+\z/ }
  #validates :email,             presence: true, uniqueness: true
  validates :postal_code,       presence: true, length: {is: 7},  numericality: {only_integer: true}
  validates :address,           presence: true, length: {maximum: 50}
  validates :telephone_number,  presence: true, length: {in: 10..11}, numericality: {only_integer: true}
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence:true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image
  validates :name, presence:true

  validates :description, presence:true

  validates :price, presence:true, numericality: {only_integer: true, greater_than_or_equal_to: 1}

    # 商品画像のサイズ調整
  def get_item_image(width, height)
    unless item_image.attached?
      # 商品画像がない場合はimages/no-image.jpgを参照
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end


  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirm: 1, making: 2, preparing: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: { impossible: 0, waiting: 1, producting: 2, complete: 3 }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :get_customer_id, only: [:show, :edit, :update] #下記記載のget_customer_idアクションが指定のアクションに適用

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      flash[:notice] = "会員情報を更新しました"
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

  def get_customer_id
    @customer = Customer.find(params[:id])
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :get_genre_id, only: [:edit, :update]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "新しいジャンルを作成しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル情報を更新しました"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def get_genre_id
    @genre = Genre.find(params[:id])
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "登録しました。"
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "変更しました。"
    else
      render :edit
    end
  end

  def item_params
        params.require(:item).permit(:item_image, :name, :description, :genre_id, :price, :is_on_sale)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genres = Genre.all
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id).page(params[:page]).per(6)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-11 mx-auto">
      <h3><%= "#{@customer.last_name}#{@customer.first_name}さんの会員情報編集" %></h3>

      <!--バリデーション部分-->
      <%= render 'layouts/error', obj: @customer %>

      <!--form部分-->
      <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>
        <table class="table">
          <div class="py-3">
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id %></td> <!--@customerはform_withで指定されてないからインスタンス変数のまま-->
            </tr>
            <tr>
              <td>氏名</td>
              <td><%= f.text_field :last_name %> <%= f.text_field :first_name %></td>
            </tr>
            <tr>
              <td>フリガナ</td>
              <td><%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></td>
            </tr>
            <tr>
              <td>郵便番号</td>
              <td><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td><%= f.text_field :address %></td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td><%= f.text_field :telephone_number %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= f.email_field :email %></td>
            </tr>
            <tr>
              <td>会員ステータス</td>
              <td>
                <%= f.radio_button :is_active, true %>
                <%= f.label :is_active_true, "退会" %>
                <%= f.radio_button :is_active, false %>
                <%= f.label :is_active_false, "有効" %>
              </td>
            </tr>
          </div>
        </table>
        <%= f.submit "変更を保存",class: "btn btn-dark" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-11 mx-auto">
      <h3>会員一覧</h3>

      <table class="table table-bordered">
        <div class="py-3">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th>ステータス</th>
            </tr>
          </thead>

          <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td>
                <%= customer.id %>
              </td>
              <td>
                <u><%= link_to "#{customer.last_name}#{customer.first_name}", admin_customer_path(customer),  class: "text-reset" %></u>
              </td>
              <td>
                <%= customer.email %>
              </td>
              <td>
                <% if customer.is_active == true %>
                  <p class="text-secondary">退会</p>
                <% else %>
                  <p class="text-success">有効</p>
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </div>
      </table>
    </div>
  </div>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-11 mx-auto"><h3><%= "#{@customer.last_name}#{@customer.first_name}さんの会員詳細" %></h3>

      <table class="table table-bordered">
        <div class="py-3">
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %> <%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td>
              <% if @customer.is_active == true %>
                <p>退会</p>
              <% else %>
                <p>有効</p>
              <% end %>
            </td>
          </tr>
        </div>
      </table>

      <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-dark" %>
      <%= link_to "#{@customer.last_name}#{@customer.first_name}さんの注文履歴一覧", admin_path(@customer), class: "btn btn-dark" %>
    </div>
  </div>
</div>