config/routes.rb
Rails.application.routes.draw do


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :update] #:idを持たせないためresouce
    get "/customers/information/edit" => "customers#edit"
    get "/customers/confirm" => "customers#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :update, :destroy]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/confirm" => "orders#error"
    get "/orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  get '/genre/search' => 'searches#genre_search'

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "/orders/detail/:id" => "orders#detail"
    patch "/admin/order_details/:id" => "order_details#update" ,as: "order_details"
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence:true

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :get_genre_id, only: [:edit, :update]

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "新しいジャンルを作成しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル情報を更新しました"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def get_genre_id
    @genre = Genre.find(params[:id])
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-11 mx-auto">

      <h3>ジャンル編集</h3>

      <!--バリデーション部分-->
      <%= render 'layouts/error', obj: @genre %>

      <!--form部分-->
        <%= form_with model: @genre, url: admin_genre_path,method: :patch do |f| %>
          <td><%= f.label :"ジャンル名", class: "mr-3" %></td>
          <td><%= f.text_field :name, placeholder: "ジャンル名",class: "mr-5" %></td>
          <td><%= f.submit "変更を保存", class: "btn btn-dark" %></td>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-11 py-5 mx-auto">

      <h3>ジャンル一覧・追加</h3>

      <!--バリデーション部分-->
      <%= render 'layouts/error', obj: @genre %>

      <!--form部分-->
      <%=form_with model: @genre,url: admin_genres_path, method: :post do |f| %>
        <td><%= f.label :"ジャンル名", class: "mr-3" %></td>
        <td><%= f.text_field :name, class: "mr-5" %></td>
        <td><%= f.submit'新規登録',class: "btn btn-dark" %></td>
      <% end %>

      <!--ジャンル一覧-->
      <table class="table table-borderless">
        <div class="py-3">
          <thead>
            <tr>
              <th>ジャンル名</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-sm btn-dark" %></td>
            </tr>
          <%end%>
          </tbody>
        </div>
      </table>
    </div>
  </div>
</div>