config/routes.rb
Rails.application.routes.draw do


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "/about" => "homes#about", as: "about"

    resources :items, only: [:index, :show]
    resource :customers, only: [:show, :update] #:idを持たせないためresouce
    get "/customers/information/edit" => "customers#edit"
    get "/customers/confirm" => "customers#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :update, :destroy]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/confirm" => "orders#error"
    get "/orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end
  get '/genre/search' => 'searches#genre_search'

  namespace :admin do
    root to: "homes#top"
    resources :items, only: [:index, :new, :show, :edit, :create, :update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    get "/orders/detail/:id" => "orders#detail"
    patch "/admin/order_details/:id" => "order_details#update" ,as: "order_details"
  end
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :customer_id, presence: true
  validates :postal_code, presence: true, length: { is: 7 }
  validates :address, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders,     dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses,  dependent: :destroy

  validates :last_name,         presence: true, length: {maximum: 20}
  validates :last_name_kana,    presence: true, length: {maximum: 20}, format: { with: /\A[\p{katakana}\u{30fc}]+\z/ }
  validates :first_name,        presence: true, length: {maximum: 20}
  validates :first_name_kana,   presence: true, length: {maximum: 20}, format: { with: /\A[\p{katakana}\u{30fc}]+\z/ }
  #validates :email,             presence: true, uniqueness: true
  validates :postal_code,       presence: true, length: {is: 7},  numericality: {only_integer: true}
  validates :address,           presence: true, length: {maximum: 50}
  validates :telephone_number,  presence: true, length: {in: 10..11}, numericality: {only_integer: true}
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence:true

end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  belongs_to :genre

  has_one_attached :item_image
  validates :name, presence:true

  validates :description, presence:true

  validates :price, presence:true, numericality: {only_integer: true, greater_than_or_equal_to: 1}

    # 商品画像のサイズ調整
  def get_item_image(width, height)
    unless item_image.attached?
      # 商品画像がない場合はimages/no-image.jpgを参照
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      item_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    item_image.variant(resize_to_limit: [width, height]).processed
  end


  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting: 0, confirm: 1, making: 2, preparing: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

  enum production_status: { impossible: 0, waiting: 1, producting: 2, complete: 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "登録しました。"
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "変更しました。"
    else
      render :edit
    end
  end

  def item_params
        params.require(:item).permit(:item_image, :name, :description, :genre_id, :price, :is_on_sale)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def genre_search
    @genres = Genre.all
    @genre_id = params[:genre_id]
    @items = Item.where(genre_id: @genre_id).page(params[:page]).per(6)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <h2><%= obj.errors.count %>件のエラーにより保存できませんでした</h2>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mt-auto footer py-3" style="background-color: #F5A9A9">
  <div class="container-fluid">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight c 2023 NAGANO CAKE co,.ltd. All Rights Reserved.</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header style="background-color: #F5A9A9;">
  <div class="container-fluid">
    <div class="row mx-auto">
      <div class="col-3">
        <%= link_to root_path do %>
          <%= image_tag 'logo_c.jpg', style: "object-fit: cover; width: 150px; height: 80px;" %>
        <% end %>
      </div>
      <div class="col-3 mt-3 text-right">
        <% if customer_signed_in?%>
          <p><%= "ようこそ、#{current_customer.last_name}#{current_customer.first_name}さん！" %></p>
        <% end %>
      </div>
      <div class="col-6">
        <ul class="row justify-content-end my-2 list-unstyled">
          <% if customer_signed_in? %>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-regular fa-user"></i>
              <%= link_to "マイページ", customers_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-cake-candles"></i>
              <%= link_to "商品一覧", items_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-cart-shopping"></i>
              <%= link_to "カート", cart_items_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-right-from-bracket"></i>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
          <% elsif admin_signed_in? %>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-cake-candles"></i>
              <%= link_to "商品一覧", admin_items_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-users"></i>
              <%= link_to "会員一覧", admin_customers_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-cart-flatbed-suitcase"></i>
              <%= link_to "注文履歴一覧", admin_orders_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-cookie-bite"></i>
              <%= link_to "ジャンル一覧", admin_genres_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-right-from-bracket"></i>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
          <% else %>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-store"></i>
              <%= link_to "About", about_path, class: "text-decoration-none align-middle align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-cake-candles"></i>
              <%= link_to "商品一覧", items_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-regular fa-handshake"></i>
              <%= link_to "新規登録", new_customer_registration_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
            <li class="nav-item mx-2 mt-2">
              <i class="fa-solid fa-right-to-bracket"></i>
              <%= link_to "ログイン", new_customer_session_path, class: "text-decoration-none align-middle", style: "color: #3B240B" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/e8ca5afb42.js" crossorigin="anonymous"></script>
    <%# ↓ここから %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru&display=swap" rel="stylesheet">
    <%# ↑ここまでGoogle Font導入 %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column h-100" style="color: #3B240B; background-color: #F6D8CE; font-family: 'Kiwi Maru', serif;">
    <%# ↑の行のfont-familyでフォント名を指定 %>
    <%= render 'layouts/header' %>
    <main class="container flex-shrink-0">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>